import type { Metadata } from "next"
import { Recursive, Inter } from "next/font/google"
import "@/styles/globals.scss"


const inter = Inter({
	variable: "--font-inter",
	subsets: [ "latin" ],
})

const recursive = Recursive({
	variable: "--font-mono",
	subsets: [ "latin" ],
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={ `${inter.variable} ${recursive.variable}` }>
				{ children }
			</body>
		</html>
	)
}
